osx_image: xcode9.0
language: swift

cache: cocoapods
podfile: Podfile

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod update
  - pod install

script:
  - set -o pipefail
  - xcodebuild -list
  - xcodebuild -workspace Findme.xcworkspace -scheme Findme -destination "platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty

after_success:
  - sleep 3
